# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Cypress Tests

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js 22
        uses: actions/setup-node@v2

        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests with Chrome
        run: npm run cy:run

        env:
          CI: true

        continue-on-error: true
